version: '3.7'

services:
  main_service:
    build:
      context: ./main_service
    ports:
      - "5050:5050"
    # runtime: nvidia  # Ensure the NVIDIA runtime is specified
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    #           count: all

  model_1:
    build:
      context: ./model1
    ports:
      - "5051:5051"
    # runtime: nvidia  # Ensure the NVIDIA runtime is specified
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    #           count: all

  model_2:
    build:
      context: ./model2
    ports:
      - "5052:5052"
    # runtime: nvidia  # Ensure the NVIDIA runtime is specified
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    #           count: all
