version: '3'
services:
  main_service:
    build:
      context: ./main_service
    ports:
      - "5000:5000"

  model_1:
    build:
      context: ./model1
    ports:
      - "5001:5001"

  model_2:
    build:
      context: ./model2
    ports:
      - "5002:5002"
