version: '3'
services:
  main_service:
    build:
      context: ./main_service
    ports:
      - "5050:5050"

  model_1:
    build:
      context: ./model1
    ports:
      - "5051:5051"

  model_2:
    build:
      context: ./model2
    ports:
      - "5052:5052"
