version: '3.7'

services:
  main_service:
    build:
      context: ./main_service
    ports:
      - "5050:5050"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  model_1:
    build:
      context: ./model1
    ports:
      - "5051:5051"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  model_2:
    build:
      context: ./model2
    ports:
      - "5052:5052"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
