# Use the official Python image as the base image
FROM python:3.10

# Install necessary dependencies for GPU support
FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install the required dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code to the working directory
COPY . .

# Set environment variables for TensorFlow GPU compatibility
ENV TF_FORCE_GPU_ALLOW_GROWTH=true
ENV TF_XLA_FLAGS=--tf_xla_auto_jit=2

# Set the entrypoint command to run the Flask app
CMD ["python", "flask_gpu1.py"]
